### ISSUE TITLE
Clone-0.40 crashes DBIx::Class

### ISSUE THREAD

**Issue by h3kker** [garu/Clone#10]
Hi!
I was trying to update my environment to the latest versions, but I failed to install DBIx::Class after updating Clone to 0.40. 
Some tests suddenly crash with segmentation faults:

- t/19retrieve_on_insert.t
- t/prefetch/correlated.t
- t/sqlmaker/bind_transport.t
- t/sqlmaker/limit_dialects/first_skip.t
- t/sqlmaker/limit_dialects/rno.t
- t/sqlmaker/limit_dialects/skip_first.t

Tested with perl-5.28.0 and perl-5.24.3
After downgrading to Clone-0.39 the tests run fine.
Thanks,
Heinz

**Comment by Kolunchik** [comment]
Confirm, perl 5.24.3, amd64

**Comment by atoomic** [comment]
going to check what's wrong there

**Comment by atoomic** [comment]
need a debug perl but can reproduce the issue while running `perl -Ilib t/19retrieve_on_insert.t` under gdb with perl 5.28.0 and DBIx::Class v0.082841

```perl
# gdb output
ok 1 - Default insert successful
ok 2 - Without retrieve_on_insert, check rank

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7a07d15 in Perl_newSVhek () from /usr/local/cpanel/3rdparty/perl/528/lib/perl5/5.28.0/x86_64-linux-64int/CORE/libperl.so
```

**Comment by atoomic** [comment]
no surprise it's coming from 4435df7edb07a6ac2084af5f4eda24a128d968b0

**Comment by atoomic** [comment]
it appears that the COWRefcnt on the COWed PV is 0...
clone is called from Hash::Merge
```
clone called...  at /usr/local/cpanel/3rdparty/perl/528/lib/perl5/cpanel_lib/Hash/Merge.pm line 223, <ARGV> line 1.
	Hash::Merge::merge() called at lib/DBIx/Class/ResultSet.pm line 3972
	DBIx::Class::ResultSet::_merge_attr() called at lib/DBIx/Class/ResultSet.pm line 647
	DBIx::Class::ResultSet::_normalize_selection() called at lib/DBIx/Class/ResultSet.pm line 336
	DBIx::Class::ResultSet::new() called at lib/DBIx/Class/Storage/DBI.pm line 2032
	DBIx::Class::Storage::DBI::insert() called at lib/DBIx/Class/Row.pm line 408
	DBIx::Class::Row::insert() called at lib/DBIx/Class/ResultSet.pm line 2894
	DBIx::Class::ResultSet::create() called at t/19retrieve_on_insert.t line 27
	Test::Exception::lives_ok() called at t/19retrieve_on_insert.t line 27
```

**Comment by atoomic** [comment]
Strangely we can get some COWPV with a COWREFCNT=0... not sure why and if it's real valid, the current fix will simply leave alone such PV... 

we can consider fixing the clone or also the source when we see such a thing but not sure it's a good idea for now...
putting that patch here to do not lost it if needed later 
```diff
diff --git a/Clone.xs b/Clone.xs
index 0e840f1..78721fa 100755
--- a/Clone.xs
+++ b/Clone.xs
@@ -198,6 +198,13 @@ sv_clone (SV * ref, HV* hseen, int depth)

         } else {
           clone = newSVsv (ref);
+
+          /* just fixed our clone... */
+          if ( SvIsCOW(clone) && !SvOOK(clone) && CowREFCNT(clone) == 0 ) {
+            SvIsCOW_off(clone); /* drop the COW flag on the clone if CowREFCNT == 0 */
+              //SvIsCOW_off(ref);
+          }
+
         }
 #else
         clone = newSVsv (ref);
```

**Comment by atoomic** [comment]
after some extra checks the suggested patch is probably not good enough, I would suggest to revert 4435df7 for now

**Comment by atoomic** [comment]
d9fad1a seems to be a better alternate for now, the addition was to bypass the COW clone when LEN=0

**Comment by garu** [comment]
Thanks @h3kker, @Kolunchik and @eserte for identifying and confirming the issue, and thanks @atoomic for the thorough debugging and fixing. After merging the fix I was able to install DBI, DBIx::Class without issues on 5.28.0.

I was not able to install MBRADSHAW/Mail-Milter-Authentication-2.20181024.tar.gz nor QBit::Application::Model::DBManager but checking the error log I saw nothing to do with Clone.

Please fetch Clone 0.41 on a repository near you!

@eserte is there a way to mark 0.40 as unfit for smoking?

**Comment by atoomic** [comment]
@eserte {code}: @garu 
I can confirm the SEGV of QBit-Application-Model-DBManager-0.021 using Clone 0.40 and can also confirm that the bug is fixed with d9fad1a6322e655c6163e111c76e66f1275d3385

When debugging without the fix I can notice that this is the same issue while trying to do a clone on a SvPV tagged COWPV but having a len=0...

```
BEFORE Flags 0x10004403 CUR 2 LEN 10 CowREFCNT 1 PV 0x247f6e0
BEFORE Flags 0x10004403 CUR 9 LEN 11 CowREFCNT 1 PV 0x1de6d60
BEFORE Flags 0x10004403 CUR 11 LEN 13 CowREFCNT 1 PV 0x1e24b10
BEFORE Flags 0x10004403 CUR 6 LEN 10 CowREFCNT 1 PV 0x1ec5fc0
BEFORE Flags 0x10004403 CUR 6 LEN 10 CowREFCNT 1 PV 0x1e83af0
BEFORE Flags 0x10004403 CUR 9 LEN 11 CowREFCNT 1 PV 0x1ebffc0
BEFORE Flags 0x10004403 CUR 11 LEN 13 CowREFCNT 1 PV 0x1661a90
BEFORE Flags 0x10004403 CUR 2 LEN 0 CowREFCNT 0 PV 0x1da08f0
[1]    25565 segmentation fault  perl t/qbit_application_model_dbmanager_fields.t
```

In short this is going to be fixed with the next release 0.41, but this is broken with 0.40

thanks

**Comment by atoomic** [comment]
@garu could we have a new release with that fix? otherwise I think it will bite more than one person
thanks

**Comment by garu** [comment]
@atoomic @P9GIT Clone 0.41 was out when I wrote [my comment above](https://github.com/garu/Clone/issues/10#issuecomment-433059472)! Please check if it works for you :)

**Comment by Kolunchik** [comment]
0.41 works good for me, thanks!

**Comment by P9GIT** [comment]
@garu 

0.41 works for us too. Thanks!

**Comment by eserte** [comment]
>  @eserte is there a way to mark 0.40 as unfit for smoking?

IMHO it's better that affected 3rd party modules increase the minimum Clone version in their prerequisite lists (or alternatively make sure that the minimum version is set to 0.41 if 0.40 is currently installed).
This way not only smokers will be "fixed", but also end user installations.
