### ISSUE TITLE
B::COW test dependency blocking downstream updates

### ISSUE THREAD

**Issue by pghmcfc** [garu/Clone#30]
Clone 0.44 introduced a test dependency on B::COW but that module fails its test suite on big-endian architectures (atoomic/B-COW/issues/1). A consequence of this is that as it stands, I cannot introduce the B::COW module in Fedora linux and thus cannot upgrade Clone beyond version 0.43 for now. This is likely to be an issue for other downstreams too unless they're content to disable the test suite for B::COW on big-endian architectures.

**Comment by atoomic** [comment]
I clearly need to get access one way or the other to a big endian box and debug this

**Comment by atoomic** [comment]
@pghmcfc B::COW v0.004 is fixing this via https://github.com/atoomic/B-COW/pull/4
I'm going to bump Clone to require this specific version and you should be good to go

**Comment by atoomic** [comment]
Clone v0.45 which is on its way to CPAN is fixing this issue.

**Comment by pghmcfc** [comment]
Updated OK in Fedora Rawhide:
https://koji.fedoraproject.org/koji/taskinfo?taskID=43734167
Thanks!
